services:
  - type: web
    name: my-react-app
    env: static
    staticPublishPath: /path/to/build
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - src: /*
        dest: /index.html
